[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps =
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    https://github.com/adafruit/DHT-sensor-library.git
    paulstoffregen/AltSoftSerial

; Set the Serial Monitor baud rate here:
monitor_speed = 115200
; Ignore legacy files
build_src_filter = +<*> -<legacy/main_legacy.cpp>